import { inject, Injectable } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';

@Injectable({ providedIn: 'root' })
export class IconsService {
    /**
     * Constructor
     */
    constructor() {
        const domSanitizer = inject(DomSanitizer);
        const matIconRegistry = inject(MatIconRegistry);

        // Register icon sets
        matIconRegistry.addSvgIconSet(
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/material-twotone.svg'
            )
        );
        matIconRegistry.addSvgIconSetInNamespace(
            'mat_outline',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/material-outline.svg'
            )
        );
        matIconRegistry.addSvgIconSetInNamespace(
            'mat_solid',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/material-solid.svg'
            )
        );
        matIconRegistry.addSvgIconSetInNamespace(
            'feather',
            domSanitizer.bypassSecurityTrustResourceUrl('icons/feather.svg')
        );
        matIconRegistry.addSvgIconSetInNamespace(
            'heroicons_outline',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/heroicons-outline.svg'
            )
        );
        matIconRegistry.addSvgIconSetInNamespace(
            'heroicons_solid',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/heroicons-solid.svg'
            )
        );
        matIconRegistry.addSvgIconSetInNamespace(
            'heroicons_mini',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/heroicons-mini.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'store-01',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/store-01.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'user-multiple',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/user-multiple.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'percent-square',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/percent-square.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'discount',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/Icon.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'calendar',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/calendar-01.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'show',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/Icon-1.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'venue_mgmt',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/Icon-3.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'dashboard',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/Icon-4.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'layout_mgmt',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/Icon-2.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'order',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/ticket-03.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'total_sales_info',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/money-receive-circle-2.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'current_future_sales',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/money-receive-circle-1.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'gross_sales',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/money-receive-circle-3.svg'
            )
        );
        matIconRegistry.addSvgIconInNamespace(
            'sho_sidebar',
            'administrative',
            domSanitizer.bypassSecurityTrustResourceUrl(
                'icons/sidebar/money-receive-circle.svg'
            )
        );
    }
}
