import { inject, Injectable } from "@angular/core";
import { MatIconRegistry } from "@angular/material/icon";
import { DomSanitizer } from "@angular/platform-browser";

@Injectable({ providedIn: "root" })
export class IconsService {
  /**
   * Constructor
   */
  constructor() {
    const domSanitizer = inject(DomSanitizer);
    const matIconRegistry = inject(MatIconRegistry);

    // Register icon sets
    matIconRegistry.addSvgIconSet(
      domSanitizer.bypassSecurityTrustResourceUrl("icons/material-twotone.svg"),
    );
    matIconRegistry.addSvgIconSetInNamespace(
      "mat_outline",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/material-outline.svg"),
    );
    matIconRegistry.addSvgIconSetInNamespace(
      "mat_solid",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/material-solid.svg"),
    );
    matIconRegistry.addSvgIconSetInNamespace(
      "feather",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/feather.svg"),
    );
    matIconRegistry.addSvgIconSetInNamespace(
      "heroicons_outline",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/heroicons-outline.svg",
      ),
    );
    matIconRegistry.addSvgIconSetInNamespace(
      "heroicons_solid",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/heroicons-solid.svg"),
    );
    matIconRegistry.addSvgIconSetInNamespace(
      "heroicons_mini",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/heroicons-mini.svg"),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "vendors",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/sidebar/vendors.svg"),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "users",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/sidebar/users.svg"),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "fee-taxes",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/fee-taxes.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "discounts",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/discounts.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "productions",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/productions.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "shows",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/sidebar/shows.svg"),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "venue-mgmt",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/venue-mgmt.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "dashboard",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/dashboard.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "layout-mgmt",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/layout-mgmt.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "in-purchase-sales",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/in-purchase-sales.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "order",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/sidebar/order.svg"),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "overview-total-sales-info",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/overview-total-sales-info.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "current-future-sales",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/current-future-sales.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "gross-sales",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/gross-sales.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "administrative",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/sidebar/administrative.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "layout_conf_view",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/layout_orders/view.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "layout_conf_credit-card-change",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/layout_orders/credit-card-change.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "layout_conf_mail-reply",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/layout_orders/mail-reply-02.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "layout_conf_download-05",
      domSanitizer.bypassSecurityTrustResourceUrl(
        "icons/layout_orders/download-05.svg",
      ),
    );
    matIconRegistry.addSvgIconInNamespace(
      "sho_sidebar",
      "catalogs",
      domSanitizer.bypassSecurityTrustResourceUrl("icons/sidebar/catalogs.svg"),
    );
  }
}
